title: 클라우드 보안 기술 블로그
description: 보안 솔루션&서비스팀에서 운영하는 클라우드 보안과 관련된 기술블로그.
show_downloads: true
logo: /assets/img/mzc_logo/MZC_NEW_CI_white.png

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : "google" # lunr (default), algolia, google
google:
  search_engine_id       : "014703115793692698478:xge8kh1ezej" # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true

# SEO Related
google_site_verification : "bFjWofACMg07882zo-25-Bpd9o6FFjzDUHyuOkslWGY"
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Analytics
analytics:
  provider               : "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-148730031-1"
    anonymize_ip         : # true, false (default)

# Site Author
author:
  name             : "Megazone Cloud"
  avatar           : "/assets/img/MZC_logo.png"# path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Security Service & Solution team 의, 클라우드 관련 보안 기술 블로그."
  email            :
  links:
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:cloudumbrella@mz.co.kr
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.megazone.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/megazonecloud"


plugin:
  - jekll-seo-tag